name: Build and publish Common-Knowledge services

on:
  push:
    branches:
      - dev
    paths:
      - '.env.dev'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load environment variables
        run: |
          if [ -f .env.dev ]; then
            export $(cat .env.dev | grep -v '^#' | xargs)
          fi
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV
          echo "FIX=$FIX" >> $GITHUB_ENV

      - name: Set Docker image info
        run: |
          LOWER_CASE_REPO=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/${LOWER_CASE_REPO}
          TAG_VERSION=${RELEASE}-${VERSION}-${BUILD}-${FIX}
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and push service images
        run: |
          #SERVICES=("file-processing" "data-export" "search-service" "scrapper-server" "scheduler" "cleaning-server" "GUI")
          SERVICES=("GUI")
          for SERVICE in "${SERVICES[@]}"; do
            echo "🔨 Building service: $SERVICE"
            cd $SERVICE || cd scrapper
            ls -al
            pwd
            #docker build -t $IMAGE_NAME:${SERVICE}-${TAG_VERSION} .
            docker build -t $IMAGE_NAME:${SERVICE}-${TAG_VERSION} .
            cd ..
            docker push $IMAGE_NAME:${SERVICE}-${TAG_VERSION}
          done
